// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SelectPowerParameter
double SelectPowerParameter(int po, const arma::mat& X);
RcppExport SEXP _PreGraphModeling_SelectPowerParameter(SEXP poSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type po(poSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(SelectPowerParameter(po, X));
    return rcpp_result_gen;
END_RCPP
}
// ComputeAtanMean
double ComputeAtanMean(double theta, double power, int max_val);
RcppExport SEXP _PreGraphModeling_ComputeAtanMean(SEXP thetaSEXP, SEXP powerSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeAtanMean(theta, power, max_val));
    return rcpp_result_gen;
END_RCPP
}
// ComputeLogNormalizingConstant
double ComputeLogNormalizingConstant(double lambda_val, double beta_sum, double power, int max_val);
RcppExport SEXP _PreGraphModeling_ComputeLogNormalizingConstant(SEXP lambda_valSEXP, SEXP beta_sumSEXP, SEXP powerSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    Rcpp::traits::input_parameter< double >::type beta_sum(beta_sumSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeLogNormalizingConstant(lambda_val, beta_sum, power, max_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PreGraphModeling_SelectPowerParameter", (DL_FUNC) &_PreGraphModeling_SelectPowerParameter, 2},
    {"_PreGraphModeling_ComputeAtanMean", (DL_FUNC) &_PreGraphModeling_ComputeAtanMean, 3},
    {"_PreGraphModeling_ComputeLogNormalizingConstant", (DL_FUNC) &_PreGraphModeling_ComputeLogNormalizingConstant, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PreGraphModeling(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
