# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SelectPowerParameter <- function(po, X) {
    .Call('_PreGraphModeling_SelectPowerParameter', PACKAGE = 'PreGraphModeling', po, X)
}

ComputeAtanMean <- function(theta, power, max_val = 100L) {
    .Call('_PreGraphModeling_ComputeAtanMean', PACKAGE = 'PreGraphModeling', theta, power, max_val)
}

ComputeLogNormalizingConstant <- function(lambda_val, beta_sum, power, max_val = 100L) {
    .Call('_PreGraphModeling_ComputeLogNormalizingConstant', PACKAGE = 'PreGraphModeling', lambda_val, beta_sum, power, max_val)
}
